name: genai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - runware>=0.4.17
    - aiofiles>=23.2.1
    - python-dotenv>=1.0.1
    - websockets>=12.0
    - requests>=2.31.0 