CREATE TABLE "test_game" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_game_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"isActive" boolean DEFAULT true NOT NULL
);
--> statement-breakpoint
CREATE TABLE "test_game_round" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_game_round_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gameId" integer NOT NULL,
	"roundNumber" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"content" text NOT NULL
);
--> statement-breakpoint
CREATE TABLE "test_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "test_session" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_session_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"gameId" integer,
	"isPlayer" boolean DEFAULT false NOT NULL,
	"avatar" text DEFAULT '' NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "test_submission" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_submission_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"gameRound" integer NOT NULL,
	"content" text NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);
--> statement-breakpoint
CREATE TABLE "test_vote" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "test_vote_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sessionId" integer NOT NULL,
	"gameRoundId" integer NOT NULL,
	"voteValue" integer NOT NULL
);
--> statement-breakpoint
CREATE INDEX "game_name_idx" ON "test_game" USING btree ("name");--> statement-breakpoint
CREATE INDEX "game_round_game_idx" ON "test_game_round" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "name_idx" ON "test_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "session_game_idx" ON "test_session" USING btree ("gameId");--> statement-breakpoint
CREATE INDEX "submission_session_idx" ON "test_submission" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "submission_game_round_idx" ON "test_submission" USING btree ("gameRound");--> statement-breakpoint
CREATE INDEX "vote_session_idx" ON "test_vote" USING btree ("sessionId");--> statement-breakpoint
CREATE INDEX "vote_game_round_idx" ON "test_vote" USING btree ("gameRoundId");